filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/backend_logs/*.log
    tags: ["backend_logs"]

  - type: log
    enabled: true
    paths:
      - /var/log/test_logs/*.log
    tags: ["test_logs"]

filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog*"]
      processors:
        - drop_event:
          when:
            not:
              or:
                - regexp:
                    message: 'error|critical|failed|unauthorized'
                - equals:
                    log.level: "error"
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log*"]
      processors:
        - drop_event:
            when:
              not:
                or:
                  - regexp.message: 'Failed password for'
                  - regexp.message: 'authentication failure'
                  - regexp.message: 'sudo:.*incorrect password'
                  - regexp.message: 'sudo:.*authentication failure'

output.logstash:
  hosts: ["logstash:5044"]
