# /etc/logstash/pipelines.yml

- pipeline.id: otx_pipeline
  path.config: "/usr/share/logstash/config/pipeline/logstash-otx.conf"
- pipeline.id: main_logs_pipeline
  path.config: "/usr/share/logstash/config/pipeline/logstash.conf"
