name: Brute Force Login Attempt Detection
type: frequency
index: dangerous*
num_events: 10
timeframe:
  seconds: 600

filter:
  - term:
      tags: "failed_password"

alert:
  - "telegram"
  - "command"

alert_text_type: alert_text_only
# alert_text: "(SIEM Alert) Possible brute-force login from IP: {0}"
alert_text: "(SIEM Alert) Possible brute-force login from IP: {{ _source.ip }}"
alert_text_args:
  - _source.ip

command:
  - "/usr/local/bin/block_ip.sh"
  - "{{ match.source.ip }}"
