name: High Traffic Alert
type: frequency
index: dangerous*
num_events: 1000
timeframe:
  minutes: 1

filter:
  - term:
      tags: "high_traffic"

alert:
  - "telegram"
  - "command"

alert_text_type: alert_text_only
# alert_text: "(SIEM Alert) High traffic (≈{1} hits/min) from IP: {0}"
alert_text: "(SIEM Alert) High traffic (≈{1} hits/min) from IP: {{ _source.ip }}"
alert_text_args:
  - _source.ip
  - num_hits

command:
  - "/usr/local/bin/block_ip.sh"
  - "{{ match.source.ip }}"