name: Malicious IP Alert
type: frequency
index: dangerous*
num_events: 1
timeframe: 30
filter:
  - term:
      tags: "malicious_ip"
alert:
  - "telegram"
  - "command"

alert_text_type: alert_text_only
alert_text: "(SIEM Alert) Malicious IP detected: {{ _source.ip }}"
alert_text_args:
  - _source.ip

command:
  - "/usr/local/bin/block_ip.sh"
  - "{{ match.source.ip }}"