name: Suspicious Activity Detected
type: any
index: dangerous*
filter:
  - terms:
      tags: ["malicious_ip","failed_password","sudo_auth_failure","firewall_denied_or_blocked"]

alert:
  - "telegram"

alert_text_type: alert_text_jinja
alert_text: |
  🚨 SIEM Alert: Suspicious activity detected  
  • IP: {{ _source.ip }}  
  • Tags: {{ tags | join(", ") }}
